/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { folder, useControls } from "leva";

type GLTFResult = GLTF & {
  nodes: {
    dutch_ship_large_01_hull: THREE.Mesh;
    dutch_ship_large_01_rigging: THREE.Mesh;
    dutch_ship_large_01_sails: THREE.Mesh;
  };
  materials: {
    dutch_ship_large_01_hull: THREE.MeshStandardMaterial;
    dutch_ship_large_01_rigging: THREE.MeshStandardMaterial;
    dutch_ship_large_01_sails: THREE.MeshStandardMaterial;
  };
};

export function Ship(props: JSX.IntrinsicElements["group"]) {
  const { sails, rigs, hull } = useControls("Ship", {
    colors: folder({
      sails: {
        value: "white",
      },
      rigs: {
        value: "white",
      },
      hull: {
        value: "white",
      },
    }),
  });

  const { nodes, materials } = useGLTF(
    "/models/ship/dutch_ship_large_01_4k.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.dutch_ship_large_01_hull.geometry}
        material={materials.dutch_ship_large_01_hull}
        material-color={hull}
      />
      <mesh
        geometry={nodes.dutch_ship_large_01_rigging.geometry}
        material={materials.dutch_ship_large_01_rigging}
        material-color={rigs}
      />
      <mesh
        geometry={nodes.dutch_ship_large_01_sails.geometry}
        material={materials.dutch_ship_large_01_sails}
        material-color={sails}
      />
    </group>
  );
}

useGLTF.preload("/models/ship/dutch_ship_large_01_4k.gltf");
